services:
  kafka-1:
    image: apache/kafka
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092, CONTROLLER://:9093, PLAINTEXT_HOST://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092, PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  #REDIS

  redis-node-0:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-0
    ports:
      - "7000:6379"
      - "17000:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-1:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-1
    ports:
      - "7001:6379"
      - "17001:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      "--masterauth", "redis-stack",
    ]

  redis-node-2:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-2
    ports:
      - "7002:6379"
      - "17002:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-3:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-3
    ports:
      - "7003:6379"
      - "17003:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-4:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-4
    ports:
      - "7004:6379"
      - "17004:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-5:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-node-5
    ports:
      - "7005:6379"
      - "17005:16379" #cluster bus port
    networks:
      - redis-cluster-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-cluster:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: redis-cluster
    ports:
      - "7006:6379"
      - "17006:16379" #cluster bus port
    command: redis-cli  --cluster create redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 --cluster-replicas 1 -a redis-stack
    networks:
      - redis-cluster-network
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5

#the clusters ( 3 masters, 3 slaves) was created with this command:  sudo docker compose exec redis-node-0 redis-cli  --cluster create redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 --cluster-replicas 1 -a thePassword
# check cluster info: sudo docker compose exec redis-node-0 redis-cli -a redis-stack cluster info
#check cluster nodes: sudo docker compose exec redis-node-0 redis-cli -a redis-stack cluster nodes

networks:
  redis-cluster-network:
    driver: bridge




