networks:
  zeco-eats-network:
    driver: bridge

services:
  ##KEYCLOAK
  keycloak-1:
    networks:
      - zeco-eats-network
    ports:
      - "8080:8080"
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      start-dev

  ##KAFKA
  kafka-controller-1:
    networks:
      - zeco-eats-network
    image: apache/kafka:3.9.0
    container_name: kafka-controller-1
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-controller-1-data:/var/lib/kafka/data

  kafka-controller-2:
    networks:
      - zeco-eats-network
    image: apache/kafka:3.9.0
    container_name: kafka-controller-2
    environment:
      KAFKA_NODE_ID: 2
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-controller-2-data:/var/lib/kafka/data

  kafka-controller-3:
    networks:
      - zeco-eats-network
    image: apache/kafka:3.9.0
    container_name: kafka-controller-3
    environment:
      KAFKA_NODE_ID: 3
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-controller-3-data:/var/lib/kafka/data

  kafka-broker-1:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-1
    networks:
      - zeco-eats-network
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-broker-1-data:/var/lib/kafka/data
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-2:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-2
    networks:
      - zeco-eats-network
    ports:
      - 29093:9092
    environment:
      KAFKA_NODE_ID: 5
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-2:19092,PLAINTEXT_HOST://localhost:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-broker-2-data:/var/lib/kafka/data
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-3:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-3
    networks:
      - zeco-eats-network
    ports:
      - 29094:9092
    environment:
      KAFKA_NODE_ID: 6
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-3:19092,PLAINTEXT_HOST://localhost:29094'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-broker-3-data:/var/lib/kafka/data
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  #REDIS

  redis-node-0:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-0
    ports:
      - "7000:6379"
      - "17000:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-1:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-1
    ports:
      - "7001:6379"
      - "17001:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",
    ]

  redis-node-2:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-2
    ports:
      - "7002:6379"
      - "17002:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-3:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-3
    ports:
      - "7003:6379"
      - "17003:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-4:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-4
    ports:
      - "7004:6379"
      - "17004:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

  redis-node-5:
    image: redis/redis-stack-server:7.4.2
    container_name: redis-node-5
    ports:
      - "7005:6379"
      - "17005:16379" #cluster bus port
    networks:
      - zeco-eats-network
    command: [
      "redis-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "nodes.conf",
      "--cluster-node-timeout", "5000",
      "--appendonly", "yes",
      "--requirepass", "redis-stack",
      "--masterauth", "redis-stack",
      #"--cluster-announce-ip", "redis-node-0",
      #"--cluster-announce-port", "6379",
      #"--cluster-announce-bus-port","16379",

    ]

volumes:
  kafka-controller-1-data:
  kafka-controller-2-data:
  kafka-controller-3-data:
  kafka-broker-1-data:
  kafka-broker-2-data:
  kafka-broker-3-data:


#  redis-cluster:
#    image: redis/redis-stack-server:7.4.2
#    container_name: redis-cluster
#    ports:
#      - "7006:6379"
#      - "17006:16379" #cluster bus port
#    command: redis-cli  --cluster create redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 --cluster-replicas 1 -a redis-stack
#    networks:
#      - zeco-eats-network
#    depends_on:
#      - redis-node-0
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-

#the clusters ( 3 masters, 3 slaves) was created with this command:  sudo docker compose exec redis-node-0 redis-cli  --cluster create redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 --cluster-replicas 1 -a thePassword
# check cluster info: sudo docker compose exec redis-node-0 redis-cli -a redis-stack cluster info
#check cluster nodes: sudo docker compose exec redis-node-0 redis-cli -a redis-stack cluster nodes


    #application services
#  config-server:
#    image: zeco-eats-config-server:1.0
#    container_name: zeco-eats-config-server
#    ports:
#     - 8888:8888
#    networks:
#      - zeco-eats-network
#    volumes:
#      - /.ssh/id_rsa:/opt/zeco-eats-config-server/.ssh/id_rsa:ro
#      - /.ssh/known_hosts:/opt/zeco-eats-config-server/.ssh/known_hosts:ro
#    environment:
#      - PRIVATE_KEY_PATH=/opt/zeco-eats-config-server/.ssh/id_rsa
#      - KNOWN_HOSTS_FILE_PATH=/opt/zeco-eats-config-server/.ssh/known_hosts
#    depends_on:
#      - kafka-1
#      - redis-node-0
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-5
#
#  users-service:
#    image: zeco-eats-users-service:1.0
#    container_name: zeco-eats-users-service
#    ports:
#     - 8082:8082
#    networks:
#      - zeco-eats-network
#    depends_on:
#      - config-server
#
#  restaurant-service:
#    image: zeco-eats-restaurant-service:1.0
#    container_name: zeco-eats-restaurant-service
#    ports:
#     - 8081:8081
#    networks:
#      - zeco-eats-network
#    depends_on:
#      - config-server
#      - users-service
#
#  deliveries-service:
#    image: zeco-eats-deliveries-service:1.0
#    container_name: zeco-eats-deliveries-service
#    ports:
#     - 8083:8083
#    networks:
#      - zeco-eats-network
#    depends_on:
#      - config-server
#      - users-service
#












