spring:
  config:
    import: optional:configserver:http://zeco-eats-config-server.zeco-eats-cluster:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${loadBalancerProtocol}://${loadBalancerURL}:${loadBalancerPort}/auth/realms/zeco-eats-realm
          jwk-set-uri: ${loadBalancerProtocol}://${loadBalancerURL}:${loadBalancerPort}/auth/realms/zeco-eats-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      redis-route-definition-repository: #redis location is already configured in application.yml( config server)
        enabled: true
      default-filters:
        - SecureHeaders
        - name: Retry
          args:
            retries: 3
            statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
        - name: RequestRateLimiter #rate limiter
          args:
            redis-rate-limiter:
              key-resolver: "#{@customKeyResolver}"
              replenishRate: 10 # Allow up to 10 requests/sec per user
              burstCapacity: 20 # Allow bursts up to 20 tokens
              requestedTokens: 1 # use 1 token per request
              deny-empty-key: false #use true in prod

      routes:
        # Config Server Route
        - id: config-server
          uri: http://zeco-eats-config-server.zeco-eats-cluster:8888
          predicates:
            - Path=/api/configServer/**

        # keycloak Route
        - id: keycloak
          uri: http://zeco-eats-keycloak.zeco-eats-cluster:8080
          predicates:
            - Path=/auth/**
          filters:
#            - SetRequestHeader=X-Forwarded-Proto, ${loadBalancerProtocol}
#            - SetRequestHeader=X-Forwarded-Host, ${loadBalancerURL}
#            - SetRequestHeader=X-Forwarded-Port, ${loadBalancerPort}
#            - MapRequestHeader=X-Forwarded-For, X-Forwarded-For
            - MapRequestHeader=authorization, authorization
            - name: SecureHeaders
              args:
                frame-options: "SAMEORIGIN"
                content-security-policy: "default-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self'"

        # Deliveries Service Route
        - id: deliveries-service
          uri: http://zeco-eats-deliveries-service.zeco-eats-cluster:8083
          predicates:
            - Path=/api/deliveries/**, /_p/api/deliveries/**

        # Restaurants Service Route
        - id: restaurants-service
          uri: http://zeco-eats-restaurants-service.zeco-eats-cluster:8081
          predicates:
            - Path=/api/restaurants/**, /_p/api/restaurants/**

        # Users Service Route
        - id: users-service
          uri: http://zeco-eats-users-service.zeco-eats-cluster:8082
          predicates:
            - Path=/api/users/**, /_p/api/users/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /api/apiGateway/actuator
  metrics:
    tags:
      service: api-gateway