server:
  port: 8083
spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: delivery-service

  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:7000
          - 127.0.0.1:7001
          - 127.0.0.1:7002 #127.0.0.1 = localhost
          - 127.0.0.1:7003
          - 127.0.0.1:7004
          - 127.0.0.1:7005
      password: redis-stack
      timeout: 60000
      ssl:
        enabled: false




