spring:
  config:
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/users/actuator
  endpoint:
    health:
      show-details: always
