spring:
  config:
    import: optional:configserver:http://zeco-eats-config-server.zeco-eats-cluster-namespace:8888

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /api/users/actuator
