name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      also-build-its-dependencies:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -pl ${{ inputs.service-name }} ${{ inputs.also-build-its-dependencies}}
