name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: ["zeco-eats CI"]
    types:
      - completed

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read



jobs:
  determine-changes:
    uses: ./.github/workflows/modified-services.yml


  deploy-custom-prometheus:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.customPrometheus-changed == 'true' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      dockerfile-path: monitoring/prometheus/Dockerfile
      ecr-repository: zeco-eats-prometheus
      ecs-service: zeco-eats-prometheus-service
      ecs-task-def-path: ecs/monitoring/prometheus/prometheus-task-def:1.json
      container-name: zeco-eats-prometheus-container

  deploy-api-gateway:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.apiGateway-changed == 'true' }}  # Only run if CI succeeded
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      dockerfile-path: apiGateway/Dockerfile
      ecr-repository: zeco-eats-api-gateway
      ecs-service: zeco-eats-api-gateway-service
      ecs-task-def-path: ecs/apiGateway/api-gateway-task-def:1.json
      container-name: zeco-eats-api-gateway-container

  deploy-config-server:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.configServer-changed == 'true' }}  # Only run if CI succeeded
    uses: ./.github/workflows/deploy.yml
    secrets:
      CONFIG_SERVER_GITHUB_PASSWORD: ${{ secrets.CONFIG_SERVER_GITHUB_PASSWORD }}
    with:
      dockerfile-path: configServer/Dockerfile
      ecr-repository: zeco-eats-config-server
      ecs-service: zeco-eats-config-server-service-q
      ecs-task-def-path: ecs/configServer/config-server-task-def:1.json
      container-name: zeco-eats-config-server-container



  deploy-restaurant-service:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.restaurants-changed == 'true' }}  # Only run if CI succeeded
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      dockerfile-path: restaurants/Dockerfile
      ecr-repository: zeco-eats-restaurant-service
      ecs-service: zeco-eats-restaurants-service-service
      ecs-task-def-path: ecs/restaurants/restaurants-task-def:1.json
      container-name: zeco-eats-restaurants-service-task-def



  deploy-delivery-service:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.deliveries-changed == 'true' }}  # Only run if CI succeeded
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      dockerfile-path: deliveries/Dockerfile
      ecr-repository: zeco-eats-deliveries-service
      ecs-service: zeco-eats-deliveries-service-service
      ecs-task-def-path: ecs/deliveries/deliveries-task-def:1.json
      container-name: zeco-eats-deliveries-service-container


  deploy-users-service:
    needs: determine-changes
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.determine-changes.outputs.userManagement-changed == 'true' }}  # Only run if CI succeeded
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      dockerfile-path: userManagement/users/Dockerfile
      ecr-repository: zeco-eats-users-service
      ecs-service: zeco-eats-users-service-service
      ecs-task-def-path: ecs/users/users-task-def:1.json
      container-name: zeco-eats-users-service-task-def
