name: zeco-eats CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  determine-changes:
    uses: ./.github/workflows/modified-services.yml


    # JOB to build config server service
  build-apiGateway:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.apiGateway-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'apiGateway'
      skip-tests: true

    # JOB to build config server service
  build-configServer:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.configServer-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'configServer'


  # JOB to build deliveries service
  build-deliveries:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.deliveries-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'deliveries'
      also-build-its-dependencies: '-am'

  # JOB to build restaurant service
  build-restaurants:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.restaurants-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'restaurants'
      also-build-its-dependencies: '-am'

  # JOB to build common service
  build-common:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.common-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'common'
      also-build-its-dependencies: '-amd'


  # JOB to build deliveries service
  build-userManagement:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.userManagement-changed == 'true' }}
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: 'userManagement/users,userManagement/keycloakCustom,'

