name: Determine modified Services

on:
  workflow_call:
    outputs:
      customPrometheus-changed:
        description: 'Indicates if prometheus module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.customPrometheus-changed }}
      apiGateway-changed:
        description: 'Indicates if api gateway module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.apiGateway-changed }}
      configServer-changed:
        description: 'Indicates if configServer module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.configServer-changed }}
      deliveries-changed:
        description: 'Indicates if deliveries module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.deliveries-changed }}
      restaurants-changed:
        description: 'Indicates if restaurants module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.restaurants-changed }}
      common-changed:
        description: 'Indicates if common module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.common-changed }}
      userManagement-changed:
        description: 'Indicates if userManagement module have new any modifications'
        value: ${{ jobs.determine-changes.outputs.userManagement-changed }}
jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      customPrometheus-changed: ${{ steps.filter.outputs.customPrometheus }}
      apiGateway-changed: ${{ steps.filter.outputs.apiGateway }}
      configServer-changed: ${{ steps.filter.outputs.configServer }}
      deliveries-changed: ${{ steps.filter.outputs.deliveries }}
      restaurants-changed: ${{ steps.filter.outputs.restaurants }}
      common-changed: ${{ steps.filter.outputs.common }}
      userManagement-changed: ${{ steps.filter.outputs.userManagement }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            customPrometheus:
            - 'monitoring/prometheus/**'
            apiGateway:
            - 'apiGateway/**'
            - 'pom.xml' #root POM affects all services
            configServer:
              - 'configServer/**'
              - 'pom.xml' #root POM affects all services
            deliveries:
              - 'deliveries/**'
              - 'pom.xml' #root POM affects all services
            restaurants:
              - 'restaurants/**'
              - 'pom.xml' #root POM affects all services
            common:
              - 'common/**'
              - 'pom.xml' #root POM affects all services
            userManagement:
              - 'userManagement/**'
              - 'pom.xml' #root POM affects all services
